##############################################################
# +--------------------------------------------------------+ #
# |              EasyMOTD 1.0.0 Config Notes               | #
# +--------------------------------------------------------+ #
##############################################################

# Do not use the /reload command as it may cause errors loading the configuration file.
# Instead please use /stop to restart your server and load new/updated configurations.
# Version 1.0.1 onwards has the /easymotd reload command, however, its use is not recommended.
# /easymotd reload command requires the permission "easymotd.reload".

# WARNING: Do not change or remove this option.
configuration-version: 1.1.0

##############################################################
# +--------------------------------------------------------+ #
# |              EasyMOTD 1.0.0 Configuration              | #
# +--------------------------------------------------------+ #
##############################################################

# MOTD Ping Message: 
# %nl% will not work in MOTD Messages!
line-1: '&6&lEasy&f&lMOTD Default Config'
line-2: '&eThis server is using EasyMOTD!'

# Fancy Playercount - Set to true to make the max player count one more than the total number of players online.
fancy-playercount: true

# Max Playercount - If you set fancy-playercount to false, set a max playercount here.
max-playercount: 16

# Server Maintenance Mode - Set tto true to kick all players trying to connect with the message defined below.
# Give players the permission "easymotd.maintenance.bypass" in order to bypass Maintenance Mode. 
# Use %nl% to start a new line. Use %player% to display the players username.
maintenance-active: true
maintenance-reason: '&4&l<!> &cUndergoing Maintenance! &4&l<!>'